feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      
server:
  error:
    include-stacktrace: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method